before_install:
  - gem update --system
  - gem --version
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - test/gemfiles/Gemfile.rails.3.0
  - test/gemfiles/Gemfile.rails.3.1
  - test/gemfiles/Gemfile.rails.3.2
notifications:
  recipients:
    - oleg@khabarov.ca
branches:
  only:
    - master
  